### ISSUE TITLE
“entrie” is not an actual word (neither in French or English)

### ISSUE THREAD

**Issue by progval** [ProjetPP/MathRecognizer#4]
https://github.com/ProjetPP/MathRecognizer/blob/19e7d25f84da1432fa43b459622434f774af4446/networktrainer.py#L45

**Comment by rcharron** [comment]
Actually I don't think it is a big problem, if you want do a pull request

**Comment by progval** [comment]
The point of issues is to keep track of things to be done.

**Comment by rcharron** [comment]
Is now entry
